STOPS = [
    {
        "id": "iad",
        "day": "Apr 23",
        "name": "Washington Dulles (IAD)",
        "time": "5:52 PM",
        "lat": 38.9531,
        "lng": -77.4565,
        "note": "Depart IAD. ~4.5 hr flight to Guatemala City.",
        "elevation": "91m",
    },
    {
        "id": "guatemala_city",
        "day": "Apr 23",
        "name": "Guatemala City",
        "time": "8:30 PM",
        "lat": 14.5832,
        "lng": -90.5270,
        "note": "Land at La Aurora International Airport, then ~1 hr shuttle to Antigua.",
        "elevation": "1,500m",
    },
    {
        "id": "antigua",
        "day": "Apr 23",
        "name": "Airbnb — Belencito, Antigua",
        "time": "~9:30 PM",
        "lat": 14.5573,
        "lng": -90.7332,
        "note": "Check in to the Belencito neighborhood house. Check-in anytime after 3 PM.",
        "elevation": "1,530m",
    },
    {
        "id": "yoga",
        "day": "Apr 24",
        "name": "Shakti Shala Yoga Studio",
        "time": "~9:00 AM",
        "lat": 14.5578,
        "lng": -90.7340,
        "note": "Morning yoga to stretch out before the big hike days ahead.",
        "elevation": "1,530m",
    },
    {
        "id": "atv_coffee",
        "day": "Apr 24",
        "name": "ATV Coffee Tour",
        "time": "3:15 PM",
        "lat": 14.5560,
        "lng": -90.7380,
        "note": "Ride ATVs to a coffee plantation, tour the farm, taste the coffee. Back in Antigua by evening.",
        "elevation": "1,530m",
    },
    {
        "id": "trailhead",
        "day": "Apr 25",
        "name": "Acatenango Trailhead",
        "time": "Early AM",
        "lat": 14.4961,
        "lng": -90.8708,
        "note": "The hike begins. Stretch, check your gear, and start the 4–5 hour ascent.",
        "elevation": "2,150m",
    },
    {
        "id": "basecamp",
        "day": "Apr 25",
        "name": "Base Camp",
        "time": "Afternoon",
        "lat": 14.4961,
        "lng": -90.8708,
        "note": "Set up camp at 3,700m. Watch Volcán de Fuego erupt across the valley all night.",
        "elevation": "3,700m",
    },
    {
        "id": "summit",
        "day": "Apr 26",
        "name": "Acatenango Summit",
        "time": "~5:30 AM",
        "lat": 14.5005,
        "lng": -90.8757,
        "note": "The crown — 3,976m. Watch sunrise paint the sky above Fuego from the top.",
        "elevation": "3,976m",
    },
    {
        "id": "return_antigua",
        "day": "Apr 26",
        "name": "Return to Antigua",
        "time": "Midday",
        "lat": 14.5573,
        "lng": -90.7332,
        "note": "Descend back to Antigua. Celebratory drinks and dinner well deserved.",
        "elevation": "1,530m",
    },
    {
        "id": "guatemala_city_dep",
        "day": "Apr 27",
        "name": "Guatemala City — Departure",
        "time": "11:55 PM",
        "lat": 14.5832,
        "lng": -90.5270,
        "note": "Head back to La Aurora for the late night flight. Makenzie departs earlier at 3 PM.",
        "elevation": "1,500m",
    },
]

TIMELINE = [
    # ── APR 23 ──
    {
        "day": "Apr 23 — Travel Day",
        "time": "5:52 PM",
        "label": "Depart IAD",
        "desc": "Flight departs Washington Dulles. ~4.5 hr flight to Guatemala City.",
        "badge": "Flight",
        "major": True,
    },
    {
        "day": "Apr 23 — Travel Day",
        "time": "8:30 PM",
        "label": "Arrive Guatemala City",
        "desc": "Land at La Aurora International Airport. Clear customs and find your shuttle to Antigua.",
        "badge": "Arrival",
        "major": True,
    },
    {
        "day": "Apr 23 — Travel Day",
        "time": "~9:30 PM",
        "label": "Check in — Belencito Airbnb",
        "desc": "~1 hour shuttle from Guatemala City. Check into the Belencito neighborhood house in Antigua. Rest up.",
        "badge": "Airbnb",
        "major": False,
    },

    # ── APR 24 ──
    {
        "day": "Apr 24 — Free Day",
        "time": "~9:00 AM",
        "label": "Yoga — Shakti Shala",
        "desc": "Morning drop-in class at Shakti Shala Yoga Studio. A good way to stretch out before two big hiking days.",
        "badge": "Wellness",
        "major": False,
    },
    {
        "day": "Apr 24 — Free Day",
        "time": "3:15 PM",
        "label": "ATV Coffee Tour",
        "desc": "Ride ATVs through the Guatemalan hills to a coffee plantation. Tour the farm, learn the process, taste everything. Rated 4.9/5.",
        "badge": "Activity",
        "major": True,
    },
    {
        "day": "Apr 24 — Free Day",
        "time": "Evening",
        "label": "Pack for the hike",
        "desc": "Lay out all your gear tonight. Fill water bottles, charge headlamps, set a very early alarm.",
        "badge": "Preparation",
        "major": False,
    },

    # ── APR 25 ──
    {
        "day": "Apr 25 — Hike Day 1",
        "time": "Early AM",
        "label": "Depart for trailhead",
        "desc": "Shuttle from Antigua to the Acatenango trailhead — about 1.5 hrs through highland villages.",
        "badge": "Transport",
        "major": False,
    },
    {
        "day": "Apr 25 — Hike Day 1",
        "time": "Morning",
        "label": "Hit the trail",
        "desc": "Path starts through farmland and coffee fields before entering pine and cloud forest. Take it steady — the altitude climbs fast.",
        "badge": "Hiking",
        "major": True,
    },
    {
        "day": "Apr 25 — Hike Day 1",
        "time": "Afternoon",
        "label": "Arrive at base camp",
        "desc": "Elevation 3,700m. Set up your tent and warm up with hot drinks. Air is thin — go slow.",
        "badge": "Camp",
        "major": True,
    },
    {
        "day": "Apr 25 — Hike Day 1",
        "time": "Night",
        "label": "Fuego eruptions",
        "desc": "Watch Volcán de Fuego erupt every ~20 minutes across the valley. Lava clearly visible in the darkness.",
        "badge": "Highlight",
        "major": True,
    },

    # ── APR 26 ──
    {
        "day": "Apr 26 — Hike Day 2",
        "time": "~4:00 AM",
        "label": "Wake up for summit push",
        "desc": "Gear up in full layers. Headlamps on. The final 276m push to the summit begins in the dark.",
        "badge": "Summit Day",
        "major": False,
    },
    {
        "day": "Apr 26 — Hike Day 2",
        "time": "~5:30 AM",
        "label": "Reach the summit (3,976m)",
        "desc": "You made it. Watch sunrise from the top of Acatenango as Fuego glows below.",
        "badge": "Summit",
        "major": True,
    },
    {
        "day": "Apr 26 — Hike Day 2",
        "time": "Morning",
        "label": "Descend",
        "desc": "Fast but tough on the knees — trekking poles earn their keep on the scree.",
        "badge": "Descent",
        "major": False,
    },
    {
        "day": "Apr 26 — Hike Day 2",
        "time": "Midday",
        "label": "Return to Antigua",
        "desc": "Shuttle back to Antigua. Shower, recover, and get ready to celebrate.",
        "badge": "Return",
        "major": True,
    },
    {
        "day": "Apr 26 — Hike Day 2",
        "time": "Evening",
        "label": "Celebratory drinks & dinner",
        "desc": "You hiked a volcano. You earned this. Antigua has excellent food and rooftop bars.",
        "badge": "Celebrate",
        "major": True,
    },

    # ── APR 27 ──
    {
        "day": "Apr 27 — Last Day",
        "time": "Daytime",
        "label": "Explore Antigua",
        "desc": "Wander the cobblestone streets, visit the cathedral ruins, browse the markets. A slow final morning.",
        "badge": "Explore",
        "major": False,
    },
    {
        "day": "Apr 27 — Last Day",
        "time": "3:00 PM",
        "label": "Makenzie departs",
        "desc": "Makenzie heads to Guatemala City for her 3 PM flight. Safe travels!",
        "badge": "Departure",
        "major": False,
    },
    {
        "day": "Apr 27 — Last Day",
        "time": "~6:00 PM",
        "label": "Late Airbnb checkout",
        "desc": "Late checkout from the Belencito house — make the most of the last hours in Antigua.",
        "badge": "Airbnb",
        "major": False,
    },
    {
        "day": "Apr 27 — Last Day",
        "time": "~9:55 PM",
        "label": "Head to Guatemala City",
        "desc": "Leave for La Aurora with plenty of time before the 11:55 PM flight.",
        "badge": "Transport",
        "major": False,
    },
    {
        "day": "Apr 27 — Last Day",
        "time": "11:55 PM",
        "label": "Depart Guatemala City",
        "desc": "Late night departure from La Aurora International Airport. See you on the other side.",
        "badge": "Flight",
        "major": True,
    },

    # ── APR 28 ──
    {
        "day": "Apr 28 — Home",
        "time": "6:08 AM",
        "label": "Arrive at IAD",
        "desc": "Touch down at Dulles. Welcome home.",
        "badge": "Home",
        "major": True,
    },
]

GEAR = [
    {
        "icon": "🧥",
        "category": "Clothing",
        "items": [
            "Windproof / waterproof jacket",
            "Warm mid-layer (fleece)",
            "Thermal base layer",
            "Gloves & warm hat",
            "Hiking pants",
            "Moisture-wicking socks (x2)",
        ],
    },
    {
        "icon": "🥾",
        "category": "Footwear",
        "items": [
            "Sturdy hiking boots (broken in)",
            "Trekking poles (rent at trailhead)",
            "Gaiters (helpful on scree)",
            "Camp shoes or sandals",
        ],
    },
    {
        "icon": "🎒",
        "category": "Pack & Shelter",
        "items": [
            "35–45L backpack",
            "Sleeping bag rated 0°C or below",
            "Sleeping bag liner",
            "Tent (or rent from operator)",
        ],
    },
    {
        "icon": "💧",
        "category": "Hydration & Food",
        "items": [
            "3L+ water capacity",
            "Water purification tablets",
            "High-energy snacks (bars, nuts)",
            "Electrolyte packets",
        ],
    },
    {
        "icon": "💡",
        "category": "Safety",
        "items": [
            "Headlamp + spare batteries",
            "First aid kit",
            "Sunscreen SPF 50+",
            "Altitude sickness pills (Diamox)",
        ],
    },
    {
        "icon": "📸",
        "category": "Optional Extras",
        "items": [
            "Camera or phone gimbal",
            "Scarf or buff (dusty trail!)",
            "Cash (USD or Quetzales)",
            "Ear plugs (very windy at camp)",
        ],
    },
]

STATS = [
    {"value": "Apr 23–28", "label": "Trip Dates"},
    {"value": "3,976m", "label": "Summit Elevation"},
    {"value": "6 Hikers", "label": "Crew"},
    {"value": "IAD → GUA", "label": "Route"},
]
